# Generated by Django 5.2 on 2025-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_image_alter_skill_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
